### ISSUE TITLE
Console Issues - Project Setup

### ISSUE THREAD

**Issue by santhosh1248** [joeldenning/coexisting-angular-microfrontends#12]
Hello,

I'm a newbie and currently facing issues while setup.
I have downloaded the project and loaded.
I have run the following scripts
cd app1
npm i
npm start

The app is running and I have tried to open [Surge.sh](http://coexisting-angular-microfrontends.surge.sh/) link and I am seeing 2 console errors by default without overriding any app.
![Screenshot (22)](https://user-images.githubusercontent.com/11964954/62302336-c9c98780-b497-11e9-8c49-6e427ea4a231.png)

Did I miss something?
Because even after overriding an app(app1), I cannot see the output

**Comment by joeldenning** [comment]
Thanks for reporting this -- it was a bug in the deployment process. See https://github.com/joeldenning/coexisting-angular-microfrontends/commit/301ab8d0047f59ed3d071838505809dc06ebc625 for the fix.

You should now be able to override app1 without a problem. In your screenshot, note that it shows `app1` as a "Default Module" instead of an `Overridden Module`. So maybe the override you tried to set up didn't work? To add an override, click on the `app1` and then add `http://localhost:4201/main.js` as the url.

Once you do, the yellow button will turn red/pink and move up into the Overridden Modules section.
