### ISSUE TITLE
How to run individual application 

### ISSUE THREAD

**Issue by devbikshu** [joeldenning/coexisting-angular-microfrontends#20]
Hi,
First thanks for great code it's really helpful.

issue:
When i am trying to run individual application eg: app1 i am not able to see any of the app1 content on the browser. So how individual application can be development when the team is not able to see what they are developing 

I tried to run individual application using ng server & npm start no output is displaying when is serve the http://localhost:4201 url 

Please guide me how to run individual application.

Regards,
Bikshapathi

**Comment by joeldenning** [comment]
Running single-spa-angular applications individually (outside of the context of single-spa) is not encouraged and intentionally not supported. The reason is that single-spa applications can depend on each other by importing each other, and that is something that doesn't work outside of single-spa + systemjs context.

You can still develop one application at a time by using import-map-overrides on a deployed environment. See [this explanation](https://github.com/joeldenning/coexisting-angular-microfrontends#an-important-note) for more info.
