### ISSUE TITLE
page refresh on child application

### ISSUE THREAD

**Issue by ponnalaxmikanth** [joeldenning/coexisting-angular-microfrontends#30]
Hi,

I have two applications loading in my portal application (app1 & app2) and they have routing.

when I navigate to child applicaiton app1/admin/route1 from portal application it is working fine and as well as  app2/admin/route1 from portal application is also working fine.

where as when I refresh the page after navigating  app1/admin/route1 getting error as page not found. how can we fix this issue?

**Comment by joeldenning** [comment]
Your web server needs to be configured for a single page application. This means that it needs to return an HTML file for all routes, instead of a 404 without the html file. See https://stackoverflow.com/questions/23442010/web-server-for-single-page-application and related issues for explanation on this.

Closing this since it's not an issue with this repo.
