### ISSUE TITLE
Refreshing app causes inconsistent rendering order of applications

### ISSUE THREAD

**Issue by Vallerious** [joeldenning/coexisting-angular-microfrontends#44]
Hi, all! Sorry for structuring this issue badly, perhaps a template for issues would be useful. :)

Steps to reproduce:
1. visit a route, for example, `/app1`
2. click the refresh button
3. Observe that the order of navbar and app1's content is switched.

This may not happen every time.

Solution:
As a solution, locally, I defined placeholders for the apps in the root-html-file -> index.html and then using domElementGetter, configured each application to load in those placeholders.

I would love to contribute for this issue, but am not sure if the index.html file is the correct place for defining the layout.

**Comment by joeldenning** [comment]
Hi Vallerious, good question. You are right that by default single-spa does not ensure a consistent dom order of applications. Recently the single-spa core team has been working on a project called single-spa-layout, which provides an easier API for ensuring dom order. The first beta of the project was released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.0-beta.0 and the preliminary documentation for it is at https://single-spa.js.org/docs/layout-overview. I view that project as the proper solution to this issue.

The alternative to single-spa-layout is to do what you've described by using domElementGetters. That approach is also a good one, and is perhaps just a bit more complex/roundabout than single-spa-layout. But both approaches work well.

If you'd like to update this example repo to use single-spa-layout, please feel free to do so.

I am closing this issue because I think I've answered the question. Feel free to comment further / reopen.

**Comment by Vallerious** [comment]
I would gladly contribute, but in the documentation I see that the javascript code uses "import" and is supposed to be put in the <script> tag...How will that work?

**Comment by joeldenning** [comment]
Most newer single-spa projects have a root config that includes both HTML and a bundled javascript file. This example, coexisting-angular-microfrontends, does not. You can inline the javascript in the HTML file by wrapping it in the following:

```html
<script>
Promise.all([System.import('single-spa'), System.import('single-spa-layout')]).then(([singleSpa, singleSpaLayout]) => {
  // do things with singleSpa and singleSpaLayout
})
</script>
```

To be able to System.import single-spa-layout, you'll have to add it to the import map. You should point to the System.register version of the library, which can be found in the `system` directory at https://unpkg.com/browse/single-spa-layout@1.0.0-beta.2/dist/

**Comment by Vallerious** [comment]
Alright, I will try it locally for my demo and then I will create a PR to the coexisting-angular-microfrontends app.

**Comment by Vallerious** [comment]
Hi, team!
I have created a PR for introducing single-spa-layout in to this project #49
