### ISSUE TITLE
Routing from NavBar to App1 or App2 route module

### ISSUE THREAD

**Issue by whebz** [joeldenning/coexisting-angular-microfrontends#6]
Hello,

I have a question:
here is my scenario:
app1 or app2 has multiple routes(ex: "app1/route1" and "app1/route2").
Is it possible to use NavBar app for navigation?
how should I defined my single-spa config?

one more thing, since I am a new in this framework, could you tell me how can I a mount my micro frontend to specific dom?

![image](https://user-images.githubusercontent.com/2911061/60589387-b1335800-9d99-11e9-8512-88f2e6a1875f.png)

thanks
webster

**Comment by joeldenning** [comment]
Hi Webster,

> Is it possible to use NavBar app for navigation?

Yes! And encouraged.

> how should I defined my single-spa config?

The [existing single-spa config](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/index.html#L40) is already set up for this.

To do this:
1. `ng g component MyNewComponent`
2. Add a route [to app-routing.module](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/app/app-routing.module.ts) and make the component be your new component.

I'm closing this since I've answered the questions, but feel free to ask further questions or reopen if there's more to discuss.

**Comment by whebz** [comment]
Thanks for response.

I have another question:
Is it possible to navigate from inside app2 to app1?
given that app2 is the only mounted app while app1 is unmounted.

**Comment by joeldenning** [comment]
> Is it possible to navigate from inside app2->subView to app1->subView? Given that app2 is the only mounted app while app1 is unmounted.

Yep! Just use `<a routerLink="/app1/subview>`. Here is [an example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/a7ee18cd020ccaf0452ef90277d98155d0cda341/app1/src/app/app.component.html#L21)
