### ISSUE TITLE
app1 does not load

### ISSUE THREAD

**Issue by arron21** [joeldenning/coexisting-angular-microfrontends#61]
after following the instructions
```
cd app1
npm i
npm start
```

and visiting http://localhost:4201/
nothing shows up

![image](https://user-images.githubusercontent.com/2738674/88561355-2779ac80-cfe4-11ea-9886-8bcb106802ff.png)

**Comment by joeldenning** [comment]
Please follow the instructions in the Readme for local developments. Single-spa applications do not each have their own HTML file, so you do not go to localhost 4201 in order to do local development for app1.

https://github.com/joeldenning/coexisting-angular-microfrontends#local-development----one-app-at-a-time
