### ISSUE TITLE
Navbar died in status SKIP_BECAUSE_BROKEN

### ISSUE THREAD

**Issue by Rexam14** [joeldenning/coexisting-angular-microfrontends#66]
When trying to run the project the following error occurs:
`Failed to load resource: the server responded with a status of 404 ()`
and the following as well:
`Uncaught Error: application 'navbar' died in status SKIP_BECAUSE_BROKEN: In this configuration Angular requires Zone.js`

No modification has been done to the code, it's just been downloaded and executed with `npm start` after `npm install`.
The error can apparently be solved by adding the following line in the `main.single-spa.ts` file:
`import 'zone.js/dist/zone';`
This makes the navbar visible on screen. However, this modification causes another error: 
`GET https://unpkg.com/zone.js@0.11.0/bundles/zone.umd.js net::ERR_ABORTED 404`

**Comment by joeldenning** [comment]
Hi @Rexam14, this is caused by the newly released zone.js@0.11.0. See https://github.com/angular/angular/pull/38473 where people have reported that the 0.11.0 release is broken.

This example repo uses an unpinned version of Zone, which is why it auto upgraded to it:

https://github.com/joeldenning/coexisting-angular-microfrontends/blob/f2f0549aab2d4fd8b3cd26ed43543b5dce66ceef/root-html-file/index.html#L23

I will fix this by pinning to 0.10.3.

**Comment by joeldenning** [comment]
Also see https://github.com/angular/angular/issues/38517

**Comment by joeldenning** [comment]
I have confirmed it is now working after #67

**Comment by hegdechinmaya** [comment]
Thanks.. i was also facing this issue. Resolved now
