### ISSUE TITLE
Current status of  support

### ISSUE THREAD

**Issue by ThielChristoph** [joeldenning/coexisting-angular-microfrontends#76]
Hello single-spa team,

I would like to use your framework as a groundwork for a rather large application for a very big company. The current skillset lies heavily in angular for this organization so this naturaly leads us to the question of the current state of support for angular. 

Are you still maintaining the angular code base but delayed compared to the angular release cycle or is it completly halted?
Thanks in advance.

**Comment by joeldenning** [comment]
I hope to create a new example for angular at some point. single-spa and single-spa-angular work with the latest versions of Angular. The reason this example has fallen behind is because when I went to create a new example using the latest version of Angular we ran into challenges with sharing the Angular library between microfrontends when using Ivy Compiler. We have since overcome those challenges, but haven't created an official example for it yet. There is a more up-to-date example by Daniil that shows Angular 11 with shared Ivy between the microfrontends.

You can read more about the single-spa-angular project status at https://github.com/single-spa/single-spa-angular#project-status. The single-spa core team doesn't have the Angular expertise to maintain this library on our own, so we rely on help from those using the library. There are a couple skilled Angular devs who help us go through the issue queues and fix bugs.

**Comment by ThielChristoph** [comment]
@joeldenning 
 
Thank you very much for your answer. I think this is enough to reason for a development on single-spa for our project. Im very excited to implement this on a large scale and will try to report back regulary.

**Comment by joeldenning** [comment]
here's the new example: https://github.com/angular-microfrontends and https://angular.microfrontends.app. It's incomplete but I've realized that I need to start telling people about it because I'm too busy to get it to a better spot and if I wait people will keep using this old coexisting-angular-microfrontends app which i do not want.

**Comment by ThielChristoph** [comment]
Thank you for the update. Its good to see that you keep on pushing for the angular side of things despite its challenges. We are already using single-spa in a micro frontend architecture and are looking forward to use the new example for our latest micro feds with angular.
